In [1]:

trajectoryDataFile=open('/home/wangyuchen/trajectory_dataset/US101/0750am-0805am/trajectories-0750am-0805am.txt')

count=0
allLineList=[]
count=0
for count,line in enumerate(trajectoryDataFile):
    #read a single line, remove space and enter
    lineList=line.split(' ')
    try:
        while True:
            lineList.remove('')
    except:
        try:
            lineList.remove('\n')
        except:
            pass
        pass
    for i in range(0,lineList.__len__()):
        # convert string to float
        lineList[i]=float(lineList[i])
    allLineList.append(lineList)
    



#read a single line, remove space and enter
# line=trajectoryDataFile.readline()
# lineList=line.split(' ')
# try:
#     while True:
#         lineList.remove('')
# except:
#     try:
#         lineList.remove('\n')
#     except:
#         pass
#     pass
# print(lineList)

In [2]:
def getValueByLable(lableList,valueList):
    """
    For instance, given a lable list ['Local_X','Local_Y'] and a value list [2.0, 24.0, 437.0, 1118846981300.0, 16.254, 
    79.349, 6451167.199, 1873312.382, 14.5, 4.9, 2.0, 39.14, -5.73, 2.0, 0.0, 13.0, 0.0, 0.0] which values sorted by the 
    order of allLableList below, the function return a value Dict {'Local_X':16.254, 'Local_Y':79.349}
    Args:
        lableList: the list of lables you've required, such as['Vehicle_ID', 'Total_Frames','Global_Time']
        valueList: the list contains all legally value, sorted by:['Vehicle_ID', 'Frame_ID','Total_Frames','Global_Time','Local_X','Local_Y','Global_X','Global_Y',\
                      'v_Length','v_Width','v_Class','v_Vel','v_Acc','Lane_ID','Preceding','Following','Space_Headway',\
                      'Time_Headway']
    Returns: 
        value list in the as the order of lableList
    For instance, given a lable list ['Local_X','Local_Y'] and a value list [2.0, 24.0, 437.0, 1118846981300.0, 16.254, 
    79.349, 6451167.199, 1873312.382, 14.5, 4.9, 2.0, 39.14, -5.73, 2.0, 0.0, 13.0, 0.0, 0.0] which values sorted by the 
    order of allLableList above, the function return a value List [16.254, 79.349]

    """
    allLableList=['Vehicle_ID', 'Frame_ID','Total_Frames','Global_Time','Local_X','Local_Y','Global_X','Global_Y',\
                  'v_Length','v_Width','v_Class','v_Vel','v_Acc','Lane_ID','Preceding','Following','Space_Headway',\
                  'Time_Headway']
    valueDictReturn={}
    for lableItem in lableList:
        valueDictReturn[lableItem]=valueList[allLableList.index(lableItem)]
    return valueDictReturn

def rearrangeDataByGlobalTime(allValueLists):
    '''
    Args:
        allValueLists: all values have been read from a txt file which have already been converted to a list
    Returns:
        dict have been arranged by global time. One single global time generally contains several value lists.
    '''
    valueDict={}
    for valueList in allValueLists:
        dictKey=getValueByLable(['Global_Time'],valueList)['Global_Time']
        if dictKey in valueDict:
            # if dictKey already there, then add valueList to the list of the key
            valueDict[dictKey].append(valueList)
        else:
            #else, create a list and append valueList on it
            valueDict[dictKey]=[valueList]
    return valueDict

maxX=0
minX=0
maxY=0
minY=0
maxV=0
minV=0
maxA=0
minA=99999999999999
for eachLine in allLineList:
    eachValueDict=getValueByLable(['Local_X','Local_Y','v_Vel','v_Acc'],eachLine)
    if eachValueDict['Local_X']>maxX:
        maxX=eachValueDict['Local_X']
    if eachValueDict['Local_X']<minX:
        minX=eachValueDict['Local_X']
    if eachValueDict['Local_Y']>maxY:
        maxY=eachValueDict['Local_Y']
    if eachValueDict['Local_Y']<minY:
        minY=eachValueDict['Local_Y']
    if eachValueDict['v_Vel']>maxV:
        maxV=eachValueDict['v_Vel']
    if eachValueDict['v_Vel']<minV:
        minV=eachValueDict['v_Vel']
    if eachValueDict['v_Acc']>maxA:
        maxA=eachValueDict['v_Acc']
    if eachValueDict['v_Acc']<minA:
        minA=eachValueDict['v_Acc']
print(maxX,minX,maxY,minY,maxV,minV,maxA,minA)
valueDict=rearrangeDataByGlobalTime(allLineList)
print('done')
print(valueDict.keys())
#keys may not in order, sorting before use keys to index frame
#keyslist=list(valueDict.keys()), keyslist.sort()



73.475 0 2195.462 0 95.3 0 11.2 -11.2
done
dict_keys([1118846980200.0, 1118846980300.0, 1118846980400.0, 1118846980500.0, 1118846980600.0, 1118846980700.0, 1118846980800.0, 1118846980900.0, 1118846981000.0, 1118846981100.0, 1118846981200.0, 1118846981300.0, 1118846981400.0, 1118846981500.0, 1118846981600.0, 1118846981700.0, 1118846981800.0, 1118846981900.0, 1118846982000.0, 1118846982100.0, 1118846982200.0, 1118846982300.0, 1118846982400.0, 1118846982500.0, 1118846982600.0, 1118846982700.0, 1118846982800.0, 1118846982900.0, 1118846983000.0, 1118846983100.0, 1118846983200.0, 1118846983300.0, 1118846983400.0, 1118846983500.0, 1118846983600.0, 1118846983700.0, 1118846983800.0, 1118846983900.0, 1118846984000.0, 1118846984100.0, 1118846984200.0, 1118846984300.0, 1118846984400.0, 1118846984500.0, 1118846984600.0, 1118846984700.0, 1118846984800.0, 1118846984900.0, 1118846985000.0, 1118846985100.0, 1118846985200.0, 1118846985300.0, 1118846985400.0, 1118846985500.0, 1118846985600.0, 11188469857

In [3]:

# the maximum number of vehicles existing at one time
theMax=0
for i in valueDict.keys():
    if theMax<valueDict[i].__len__():
        theMax=valueDict[i].__len__()
print(theMax)
print(valueDict.keys().__len__())


194
9529


In [4]:
import numpy as np
import torch

testTensor=torch.zeros((2,100))
print(testTensor[0][2])

tensor(0.)


In [5]:
maxMatrixIndex=250

#this dict record the relation between matrix index and vehicle ID in the last frame
matrixIndexAndVehicleIDRecordDict={}
#initialize dict above
for i in range(0,maxMatrixIndex):
    matrixIndexAndVehicleIDRecordDict[i]={'Vehicle_ID':-1,'refresh':-1}
matrixIndexAndVehicleIDRecordDict['time']=-1

In [6]:
import copy

def readFirstFrame(matrixIndexAndVehicleIDRecordDictParam, valueLists):
    """
    To generate the first set of tensors from the first frame
    Args:
        matrixIndexAndVehicleIDRecordDictParam: just as its name
        valueLists: a list consists of all valuelist at one time
    Returns:
        several tensors arranged by: positionTensor, speedTensor, accTensor, angleTensor,newVehicleList(type:list)
    
    """
    maxMatrixIndex=matrixIndexAndVehicleIDRecordDictParam.keys().__len__()-1
    #tensors initialize
    positionTensor=torch.zeros(2,maxMatrixIndex)
    speedTensor=torch.zeros(1,maxMatrixIndex)
    accTensor=torch.zeros(1,maxMatrixIndex)
    angleTensor=torch.zeros(1,maxMatrixIndex)
    newVehicleIDList=[]
    curMatrixIndex=0
    matrixIndexAndVehicleIDRecordDictParam['time']=getValueByLable(["Global_Time"],valueLists[0])['Global_Time']
    #fill out all tensors
    for eachValueList in valueLists:
        #get values from eachValueList, generate dict
        returnedEachValueDict=getValueByLable(['Vehicle_ID','Local_X','Local_Y','v_Vel','v_Acc'],eachValueList)
        #assign to the curMatrixIndex-th row of corresponding tensor
        #angle Tensor assignment is not neeed for the initial value of each element in it is already zero
        positionTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['Local_X'],returnedEachValueDict['Local_Y']))
        speedTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Vel']))
        accTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Acc']))
        #then handle the record matrix
        matrixIndexAndVehicleIDRecordDictParam[curMatrixIndex]['Vehicle_ID']=returnedEachValueDict['Vehicle_ID']
        matrixIndexAndVehicleIDRecordDictParam[curMatrixIndex]['refresh']=0
        newVehicleIDList.append(copy.deepcopy(returnedEachValueDict['Vehicle_ID']))
        curMatrixIndex=curMatrixIndex+1
    return positionTensor,speedTensor,accTensor,angleTensor,newVehicleIDList

In [7]:
#test readFirstFrame function
positionTensor,speedTensor,accTensor,angleTensor,newVehicleList=readFirstFrame(matrixIndexAndVehicleIDRecordDict,valueDict[1118847019700.0])


In [8]:
readFirstFrame(matrixIndexAndVehicleIDRecordDict,valueDict[1118847019700.0])
import math

def findMatrixIndexByVehicleID(matrixIndexAndVehicleIDRecordDictParam, vehicle_ID):
    for i in range(0, len(matrixIndexAndVehicleIDRecordDictParam)-1):
        if matrixIndexAndVehicleIDRecordDictParam[i]['Vehicle_ID']==vehicle_ID:
            return i
    return -1

def findEmptyMatrixIndex(matrixIndexAndVehicleIDRecordDictParam):
    for i in range(0, len(matrixIndexAndVehicleIDRecordDictParam)-1):
        if matrixIndexAndVehicleIDRecordDictParam[i]['Vehicle_ID']==-1:
            #Vehicle_ID=-1 when there is no existed vehicle ID bounding to the index
            return i
    raise Exception("NO EMPTY ELEMENT IN MATRIX")

def readGeneralFrame(matrixIndexAndVehicleIDRecordDictParam, valueLists, prePositionTensor):
    """
    To generate the first set of tensors from the general frame that have a preceding one
    Args:
        matrixIndexAndVehicleIDRecordDictParam: just as its name
        valueLists: a list consists of all valuelist at one time
        prePositionTensor: positionTensor from the preceding frame, which is used to calculate angle tensor
    Returns:
        everal tensors arranged by: positionTensor, speedTensor, accTensor, angleTensor,newVehicleList(type:list),
        vanishedVehicleList(type:list)
    
    """
    #tensors initialize
    maxMatrixIndex=matrixIndexAndVehicleIDRecordDictParam.keys().__len__()-1
    positionTensor=torch.zeros(2,maxMatrixIndex)
    speedTensor=torch.zeros(1,maxMatrixIndex)
    accTensor=torch.zeros(1,maxMatrixIndex)
    angleTensor=torch.zeros(1,maxMatrixIndex)
    newVehicleIDList=[]
    vanishedVehicleList=[]
    curMatrixIndex=0
    matrixIndexAndVehicleIDRecordDictParam['time']=getValueByLable(["Global_Time"],valueLists[0])['Global_Time']
    #fill out all tensors
    for eachValueList in valueLists:
        #get values from eachValueList, generate dict
        returnedEachValueDict=getValueByLable(['Vehicle_ID','Local_X','Local_Y','v_Vel','v_Acc'],eachValueList)
        indexOfVehicle=findMatrixIndexByVehicleID(matrixIndexAndVehicleIDRecordDictParam,returnedEachValueDict['Vehicle_ID'])
        if indexOfVehicle!=-1:
        #index exist then the vehicle already existed in the preceded frame
            matrixIndexAndVehicleIDRecordDictParam[indexOfVehicle]['refresh']=1
            curMatrixIndex=indexOfVehicle
            #assign to the curMatrixIndex-th row of corresponding tensor
            positionTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['Local_X'],returnedEachValueDict['Local_Y']))
            speedTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Vel']))
            accTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Acc']))
            angleTensor[:,curMatrixIndex]=math.atan2(positionTensor[0,curMatrixIndex]-\
                                                     prePositionTensor[0,curMatrixIndex],\
                                                    positionTensor[1,curMatrixIndex]-prePositionTensor[1,curMatrixIndex])
        else:
        #a new vehicle ID
            newVehicleIDList.append(copy.deepcopy(returnedEachValueDict['Vehicle_ID']))
            curMatrixIndex=findEmptyMatrixIndex(matrixIndexAndVehicleIDRecordDictParam)
            matrixIndexAndVehicleIDRecordDictParam[curMatrixIndex]['Vehicle_ID']=copy.deepcopy(returnedEachValueDict['Vehicle_ID'])
            matrixIndexAndVehicleIDRecordDictParam[curMatrixIndex]['refresh']=1
            #assign to the curMatrixIndex-th row of corresponding tensor
            positionTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['Local_X'],returnedEachValueDict['Local_Y']))
            speedTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Vel']))
            accTensor[:,curMatrixIndex]=torch.tensor((returnedEachValueDict['v_Acc']))
            angleTensor[:,curMatrixIndex]=math.atan2(positionTensor[0,curMatrixIndex]-\
                                                     prePositionTensor[0,curMatrixIndex],\
                                                    positionTensor[1,curMatrixIndex]-prePositionTensor[1,curMatrixIndex])
    for i in range(0,maxMatrixIndex):
    #find vanished vehicle and remove from dict
        if matrixIndexAndVehicleIDRecordDictParam[i]['refresh']==0:
            #if refresh=0 then the corresponding vehicle ID was not found in this frame
            vanishedVehicleList.append(copy.deepcopy(matrixIndexAndVehicleIDRecordDictParam[i]['Vehicle_ID']))
            matrixIndexAndVehicleIDRecordDictParam[i]['refresh']=-1
            matrixIndexAndVehicleIDRecordDictParam[i]['Vehicle_ID']=-1
    
    for i in range(0,maxMatrixIndex):
    #set all refrshed which equivalent to 1 to 0 to prepare for the next frame
        if matrixIndexAndVehicleIDRecordDictParam[i]['refresh']==1:
                #if refresh=0 then the corresponding vehicle ID was not found in this frame
                matrixIndexAndVehicleIDRecordDictParam[i]['refresh']=0

    return positionTensor,speedTensor,accTensor,angleTensor,newVehicleIDList,vanishedVehicleList


In [9]:
keys=list(valueDict.keys())
keys.sort()

#
#this dict record the relation between matrix index and vehicle ID in the last frame
matrixIndexAndVehicleIDRecordDict={}
#initialize dict above
for i in range(0,maxMatrixIndex):
    matrixIndexAndVehicleIDRecordDict[i]={'Vehicle_ID':-1,'refresh':-1}
matrixIndexAndVehicleIDRecordDict['time']=-1
positionTensor,speedTensor,accTensor,angleTensor,newVehicleList=readFirstFrame(matrixIndexAndVehicleIDRecordDict,valueDict[keys[0]])
print('Global_Time: ',matrixIndexAndVehicleIDRecordDict['time'],'new Vehicle ID: ',newVehicleList)
# for i in range(1,keys.__len__()):
#     if(i%1000==0):
#         print(i)
#     positionTensor,speedTensor,accTensor,angleTensor,newVehicleList,vanishedVehicleList\
#     =readGeneralFrame(matrixIndexAndVehicleIDRecordDict,valueDict[keys[i]],positionTensor)
#     if (newVehicleList.__len__()+vanishedVehicleList.__len__())>=1:
#         print('Global_Time: ',matrixIndexAndVehicleIDRecordDict['time'],', new vehicle ID: ',newVehicleList,\
#          ', vanished vehicle ID: ',vanishedVehicleList)
    
    
# #     print(matrixIndexAndVehicleIDRecordDict)


# for i in range(1,keys.__len__()):
#     distance=keys[i]-keys[i-1]
#     if(distance!=100):
#         print(keys[i],keys[i-1],distance)
# for i in range(0,keys.__len__()):
#     print(keys[i])

Global_Time:  1118846979700.0 new Vehicle ID:  [5.0]


In [10]:
import torch.utils.data as utils
import torch.nn.functional as F
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.parameter import Parameter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
%matplotlib inline 

In [11]:
torch.cuda.is_available()

True

In [12]:
def fromDirGenerateDict(trajectoryDir):
    trajectoryDataFile=open('/home/wangyuchen/trajectory_dataset/US101/0750am-0805am/trajectories-0750am-0805am.txt')
    count=0
    allLineList=[]
    count=0
    for count,line in enumerate(trajectoryDataFile):
        #read a single line, remove space and enter
        lineList=line.split(' ')
        try:
            while True:
                lineList.remove('')
        except:
            try:
                lineList.remove('\n')
            except:
                pass
            pass
        for i in range(0,lineList.__len__()):
            # convert string to float
            lineList[i]=float(lineList[i])
        allLineList.append(lineList)
    valueDict=rearrangeDataByGlobalTime(allLineList)
    return valueDict


In [13]:
list11=[1,2,3,4,5]
a=list11
b=a
list11[4]=999
a[3]=9
print(a)
print(b)

[1, 2, 3, 9, 999]
[1, 2, 3, 9, 999]


In [14]:
class tensorsDataset(Dataset):
    def __init__(self, trajectoryFileList, numberOfTensorsEachBatch=100,lableTensorEachBatch=10):
        if(numberOfTensorsEachBatch<5):
            raise Exception("THE NUMBER OF TENSORS IN EACH BATCH IS TOO SMALL")
        self.valueDictList=[]
        self.sizeList=[]
        self.numberOfTensorsEachBatch=numberOfTensorsEachBatch
        self.lableTensorEachBatch=lableTensorEachBatch
        self.allTensorsEachBatch=numberOfTensorsEachBatch+lableTensorEachBatch
        self.keysList=[]
        for eachFile in trajectoryFileList:
            valueDict=fromDirGenerateDict(eachFile)
            self.valueDictList.append(copy.deepcopy(valueDict))
            self.sizeList.append(valueDict.keys().__len__()-self.allTensorsEachBatch)
            sortedKeys=list(valueDict.keys())
            sortedKeys.sort()
            self.keysList.append(copy.deepcopy(sortedKeys))

    def __len__(self):
        allLen=0
        for length in self.sizeList:
            allLen=allLen+length
        return allLen
    
    def fromIdxMapToList(self,idx):
        """
        since there are several lists,we have to know which list shoud we use and the ture index in the list
        Return:
            the trueIndex, listIndex
        """
        countSection=0
        for i in range(0,self.sizeList.__len__()):
            countSection+=self.sizeList[i]
            if(idx<countSection):
                return idx-countSection+self.sizeList[i],i
            
    
    def __getitem__(self,idx):
        #initialize trueIndex, listIndex
        #
        #this dict record the relation between matrix index and vehicle ID in the last frame
        matrixIndexAndVehicleIDRecordDict={}
        #initialize dict above
        for i in range(0,maxMatrixIndex):
            matrixIndexAndVehicleIDRecordDict[i]={'Vehicle_ID':-1,'refresh':-1}
        matrixIndexAndVehicleIDRecordDict['time']=-1
        trueIndex,listIndex=self.fromIdxMapToList(idx)
        itemDict={'positionTensorList':[],'speedTensorList':[],'accTensorList':[],'angleTensorList':[],'time':[]}
        valueDict=self.valueDictList[listIndex] #valueDict is the Dict of many frames
        dictKeys=self.keysList[listIndex]
        #generate tensors of first frame
        positionTensor,speedTensor,accTensor,angleTensor,newVehicleList\
        =readFirstFrame(matrixIndexAndVehicleIDRecordDict,valueDict[dictKeys[trueIndex]])
        angleSinTensor=torch.sin(angleTensor)
        angleCosTensor=torch.cos(angleTensor)
        combinedTensor=torch.cat((positionTensor,speedTensor.mul(angleSinTensor),\
                                 speedTensor.mul(angleCosTensor),accTensor.mul(angleSinTensor),\
                                 accTensor.mul(angleCosTensor)),0)
        allCombineTensorTrain=combinedTensor.unsqueeze(0)
        allCombineTensorValid=0
#         itemDict['positionTensorList'].append(positionTensor)
#         itemDict['speedTensorList'].append(speedTensor)
#         itemDict['accTensorList'].append(accTensor)
#         itemDict['angleTensorList'].append(angleTensor)
#         time=getValueByLable(['Global_Time'],valueDict[dictKeys[trueIndex]][0]) #valueDict[sortedDitKey[theIndexOfSortedDictKey]][0]
#         itemDict['time'].append(time)
        
        for i in range(trueIndex+1,trueIndex+self.allTensorsEachBatch):
            positionTensor,speedTensor,accTensor,angleTensor,newVehicleList,vanishedVehicleList\
            =readGeneralFrame(matrixIndexAndVehicleIDRecordDict,valueDict[dictKeys[i]],positionTensor)
            angleSinTensor=torch.sin(angleTensor)
            angleCosTensor=torch.cos(angleTensor)
            combinedTensor=torch.cat((positionTensor,speedTensor.mul(angleSinTensor),\
                                     speedTensor.mul(angleCosTensor),accTensor.mul(angleSinTensor),\
                                     accTensor.mul(angleCosTensor)),0)
            if i<self.numberOfTensorsEachBatch+trueIndex:
                allCombineTensorTrain=torch.cat((allCombineTensorTrain,combinedTensor.unsqueeze(0)),0)
            elif i==self.numberOfTensorsEachBatch+trueIndex:
                allCombineTensorValid=combinedTensor.unsqueeze(0)
            else:
                allCombineTensorValid=torch.cat((allCombineTensorValid,combinedTensor.unsqueeze(0)),0)
#             itemDict['positionTensorList'].append(positionTensor)
#             itemDict['speedTensorList'].append(speedTensor)
#             itemDict['accTensorList'].append(accTensor)
#             itemDict['angleTensorList'].append(angleTensor)
#             time=getValueByLable(['Global_Time'],valueDict[dictKeys[i]][0]) #valueDict[sortedDitKey[theIndexOfSortedDictKey]]
#             itemDict['time'].append(time)
        return allCombineTensorTrain,allCombineTensorValid
# trajectoryFileList=['/home/wangyuchen/trajectory_dataset/US101/0750am-0805am/trajectories-0750am-0805am.txt',\
#                    '/home/wangyuchen/trajectory_dataset/US101/0805am-0820am/trajectories-0805am-0820am.txt',\
#                    '/home/wangyuchen/trajectory_dataset/US101/0820am-0835am/trajectories-0820am-0835am.txt']
trajectoryFileList=['/home/wangyuchen/trajectory_dataset/US101/0750am-0805am/trajectories-0750am-0805am.txt']

trajectorDataSet=tensorsDataset(trajectoryFileList)
                                 
            

In [15]:
type(trajectorDataSet)


__main__.tensorsDataset

In [16]:
dataLoader=DataLoader(trajectorDataSet,batch_size=4,shuffle=True,num_workers=4)

In [17]:
class LSTM(nn.Module):
    def __init__(self, input_size, cell_size, hidden_size, output_last = True):
        """
        cell_size is the size of cell_state.
        hidden_size is the size of hidden_state, or say the output_state of each step
        """
        super(LSTM, self).__init__()
        
        self.cell_size = cell_size
        self.hidden_size = hidden_size
        self.fl = nn.Linear(input_size + hidden_size, hidden_size)
        self.il = nn.Linear(input_size + hidden_size, hidden_size)
        self.ol = nn.Linear(input_size + hidden_size, hidden_size)
        self.Cl = nn.Linear(input_size + hidden_size, hidden_size)
        
        self.output_last = output_last
        
    def step(self, input, Hidden_State, Cell_State):
        combined = torch.cat((input, Hidden_State), 1)
        f = F.sigmoid(self.fl(combined))
        i = F.sigmoid(self.il(combined))
        o = F.sigmoid(self.ol(combined))
        C = F.tanh(self.Cl(combined))
        Cell_State = f * Cell_State + i * C
        Hidden_State = o * F.tanh(Cell_State)
        
        return Hidden_State, Cell_State
    
    def forward(self, inputs):
        batch_size = inputs.size(0)
        time_step = inputs.size(1)
        Hidden_State, Cell_State = self.initHidden(batch_size)
        
        if self.output_last:
            for i in range(time_step):
                Hidden_State, Cell_State = self.step(torch.squeeze(inputs[:,i:i+1,:]), Hidden_State, Cell_State)  
            return Hidden_State
        else:
            outputs = None
            for i in range(time_step):
                Hidden_State, Cell_State = self.step(torch.squeeze(inputs[:,i:i+1,:]), Hidden_State, Cell_State)  
                if outputs is None:
                    outputs = Hidden_State.unsqueeze(1)
                else:
                    outputs = torch.cat((outputs, Hidden_State.unsqueeze(1)), 1)
            return outputs
    
    def initHidden(self, batch_size):
        use_gpu = torch.cuda.is_available()
        if use_gpu:
            Hidden_State = Variable(torch.zeros(batch_size, self.hidden_size).cuda())
            Cell_State = Variable(torch.zeros(batch_size, self.hidden_size).cuda())
            return Hidden_State, Cell_State
        else:
            Hidden_State = Variable(torch.zeros(batch_size, self.hidden_size))
            Cell_State = Variable(torch.zeros(batch_size, self.hidden_size))
            return Hidden_State, Cell_State
        

In [18]:
dataIter=iter(dataLoader)
dataInputs,dataValid=dataIter.next()

In [19]:
print(dataInputs.size())
print(dataValid.size())
viewedDataInputs=dataInputs.view(4,100,-1)
viewedDataValid=dataValid.view(4,10,-1)
viewedDataInputs=viewedDataInputs.cuda()
viewedDataValid=viewedDataValid.cuda()
print(viewedDataInputs.size())
net=LSTM(1500,1500,1500).cuda()
output=net(viewedDataInputs)
print(output)

torch.Size([4, 100, 6, 250])
torch.Size([4, 10, 6, 250])
torch.Size([4, 100, 1500])
tensor([[ 0.0000e+00,  9.1381e-13, -1.0000e+00,  ...,  0.0000e+00,
          1.0000e+00, -1.0000e+00],
        [ 0.0000e+00,  9.4221e-03, -2.1361e-33,  ...,  4.2708e-31,
          1.0000e+00, -1.0557e-05],
        [ 1.7275e-25,  7.6159e-01,  0.0000e+00,  ...,  5.7781e-18,
          1.0000e+00, -1.0000e+00],
        [ 4.5191e-07,  7.6159e-01, -9.7974e-01,  ...,  0.0000e+00,
          1.0000e+00, -6.6325e-28]], device='cuda:0', grad_fn=<MulBackward0>)


/home/wangyuchen/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/wangyuchen/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1340: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [20]:
def tensorNormalization(inputTensor,minValue,maxValue):
    inputTensor.add_(-minValue).div_(maxValue-minValue)
    
def batchNormalizationForCombinedTensor(inputBatchedTensor,minX,maxX,minY,maxY,minV,maxV,minA,maxA):
    tensorNormalization(inputBatchedTensor[:,:,0,:],minX,maxX)
    tensorNormalization(inputBatchedTensor[:,:,1,:],minY,maxY)
    tensorNormalization(inputBatchedTensor[:,:,2:3,:],minV,maxV)
    tensorNormalization(inputBatchedTensor[:,:,4:5,:],minA,maxA)

In [21]:
dataInputs,dataValid=dataIter.next()
print(dataInputs[0,70,0,:])
batchNormalizationForCombinedTensor(dataInputs,minX,maxX,minY,maxY,minV,maxV,minA,maxA)
print(dataInputs[0,70,0,:])
print(dataInputs[0][0][0].size())

tensor([15.2570,  7.4360, 51.8760, 36.9590, 14.2130,  5.4760, 52.2140, 27.4030,
        44.5940, 51.4550,  5.3920, 55.2170, 40.9150, 16.3500,  8.7230, 37.7770,
         9.6940, 28.8070,  8.0820, 53.1010,  0.0000, 41.6660,  4.6010, 30.5350,
         8.4100, 19.1890,  7.7820, 41.4860, 51.8520, 22.1460,  9.6230, 19.2270,
        30.2700, 52.1180, 29.9330, 18.1110, 40.9620, 20.8610,  7.8260, 30.8780,
        28.3950, 41.8530, 51.4160,  7.7410, 18.7370, 51.7570, 33.5210, 20.6160,
        21.8860, 30.7940, 38.7930, 41.5850, 20.4510,  6.7560, 54.1350, 32.3670,
        32.2170, 16.3010, 55.6490, 53.2210, 28.5790,  5.8780, 43.5210, 20.4000,
         7.6550, 51.4370, 40.1800, 19.1770, 31.1100, 41.6670, 41.5560, 20.4800,
         8.0180, 31.6290, 17.9900,  8.3490, 64.1420, 51.7240, 41.0080, 20.3900,
        29.6120, 51.6420,  6.2090, 17.1700, 42.2960, 53.8060, 32.6920, 64.7850,
        19.8000,  8.3300, 40.5000, 19.6990,  8.2190, 30.0230, 55.2750, 20.8430,
        53.4690, 42.0270, 29.7820,  8.95

In [35]:
def generateAdjacencyMatrix(batchedPositionTensor,lambdaX,lambdaY,omegaX,omegaY,m):
    """
    Using batched position tensor generate batched adjacency matrix
    Args:
        batchedPositionTensor: a batch of position tensor, which size in (batch, timeSequence,2,vehicles), the 
        value 2 in dim=2 is the position of x and y. 
        lambda1,lambda2,omega1,omega2,m are parameters of the function. m<1
        see detail in my notebook
    Returns:
        a batch of adjacency matrix
    Example:
        if given a batch of combined tensor, named theTensor, which size as below:
            (4,100,6,250)
        which means 4 batches, 100 time step, 6 dimension which respectively of positonx, positony, velocityx, 
        velocityy, accx,accy.
        then we apply the function in such way:
        generateAdjacencyMatrix(theTensor(:,:,0:1,:))
    """
    print(batchedPositionTensor.size())
    sizeOfEachMatrix=batchedPositionTensor[0,0,0,:].size()[0]
    batchedPositionTensor
    for batchI in range(batchedPositionTensor.size()[0]): #revolve each batch
        print('batchI',batchI)
        for timeStepI in range(batchedPositionTensor.size()[1]):#revolve each time step
            print('timeStepI:',timeStepI)
            adjacencyMatrix=torch.zeros((sizeOfEachMatrix,sizeOfEachMatrix))
            for i in range(sizeOfEachMatrix):
                for j in range(sizeOfEachMatrix):
#                     adjacencyMatrix[i,j]=1
                    #calculate original element with linear function
                    adjacencyMatrix[i,j]=abs(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,j])*\
                        abs(batchedPositionTensor[batchI,timeStepI,0,i]-batchedPositionTensor[batchI,timeStepI,0,j])
#                     (omegaY/math.exp(lambdaX*abs(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,j])))*\
#                     (omegaX/math.exp(lambdaY*abs(batchedPositionTensor[batchI,timeStepI,0,i]-batchedPositionTensor[batchI,timeStepI,0,j])))
                    
                    #calculate original element with expenential
#                     adjacencyMatrix[i,j]=
#                     (omegaY/math.exp(lambdaX*abs(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,j])))*\
#                     (omegaX/math.exp(lambdaY*abs(batchedPositionTensor[batchI,timeStepI,0,i]-batchedPositionTensor[batchI,timeStepI,0,j])))
                    if(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,i]<0):
                        #if i follows j, then multiple m, m<1
                        adjacencyMatrix[i,j]=adjacencyMatrix[i,j]*m
            adjacencyMatrix=adjacencyMatrix.unsqueeze(0)
            if timeStepI==0:
                matrixSequenceInTimeStepDim=adjacencyMatrix
            else:
                matrixSequenceInTimeStepDim=\
                torch.cat((matrixSequenceInTimeStepDim,adjacencyMatrix),0)
        matrixSequenceInTimeStepDim=matrixSequenceInTimeStepDim.unsqueeze(0)
        if batchI==0:
            matrixSequenceInBatchDim=matrixSequenceInTimeStepDim
        else:
            matrixSequenceInBatchDim=torch.cat((matrixSequenceInBatchDim,matrixSequenceInTimeStepDim),0)            
    return matrixSequenceInBatchDim
generateAdjacencyMatrix(dataInputs[:,:,0:2,:],5,5,1,1,2.5)

torch.Size([4, 100, 2, 250])
batchI 0
timeStepI: 0
timeStepI: 1
timeStepI: 2
timeStepI: 3
timeStepI: 4
timeStepI: 5
timeStepI: 6
timeStepI: 7
timeStepI: 8
timeStepI: 9
timeStepI: 10
timeStepI: 11
timeStepI: 12
timeStepI: 13
timeStepI: 14
timeStepI: 15
timeStepI: 16
timeStepI: 17
timeStepI: 18
timeStepI: 19
timeStepI: 20
timeStepI: 21
timeStepI: 22
timeStepI: 23
timeStepI: 24
timeStepI: 25


KeyboardInterrupt: 

In [33]:
# #The test of whether CNN could be use to fitting a exponential map function.
# #result: it does converge, but meaningless
# def generateAdjacencyMatrix(batchedPositionTensor,lambdaX,lambdaY,omegaX,omegaY,m):
#     """
#     Using batched position tensor generate batched adjacency matrix
#     Args:
#         batchedPositionTensor: a batch of position tensor, which size in (batch, timeSequence,2,vehicles), the 
#         value 2 in dim=2 is the position of x and y. 
#         lambda1,lambda2,omega1,omega2,m are parameters of the function. m<1
#         see detail in my notebook
#     Returns:
#         a batch of adjacency matrix
#     Example:
#         if given a batch of combined tensor, named theTensor, which size as below:
#             (4,100,6,250)
#         which means 4 batches, 100 time step, 6 dimension which respectively of positonx, positony, velocityx, 
#         velocityy, accx,accy.
#         then we apply the function in such way:
#         generateAdjacencyMatrix(theTensor(:,:,0:1,:))
#     """
#     class mapAdjacencyMatrixNet(nn.Module):
#         def __init__(self, inputSize, outputSize):
#             super(mapAdjacencyMatrixNet,self).__init__()
#             self.layer1=nn.Linear(inputSize,outputSize)
#             self.layer2=nn.Linear(outputSize,inputSize)
#             self.outputLayer=nn.Linear(inputSize,outputSize)
#         def forward(self,inputs):
#             output=self.layer1(inputs)
#             output=F.sigmoid(output)
#             output=self.layer2(output)
#             output=F.sigmoid(output)
#             output=self.outputLayer(output)
#             return output
#     mapNet=mapAdjacencyMatrixNet(250*2,250*250)
#     mapNet.cuda()
#     mapNet.train()
#     loss_MSE = torch.nn.MSELoss()
#     loss_L1 = torch.nn.L1Loss()
#     learning_rate = 1e-5
#     optimizer = torch.optim.RMSprop(mapNet.parameters(), lr = learning_rate)
#     print(batchedPositionTensor.size())
#     sizeOfEachMatrix=batchedPositionTensor[0,0,0,:].size()[0]
#     batchedPositionTensor
#     for batchI in range(batchedPositionTensor.size()[0]): #revolve each batch
#         print('batchI',batchI)
#         for timeStepI in range(batchedPositionTensor.size()[1]):#revolve each time step
#             print('timeStepI:',timeStepI)
#             adjacencyMatrix=torch.zeros((sizeOfEachMatrix,sizeOfEachMatrix))
#             for i in range(sizeOfEachMatrix):
#                 for j in range(sizeOfEachMatrix):
# #                     adjacencyMatrix[i,j]=1
                    
#                     #calculate original element 
#                     adjacencyMatrix[i,j]=\
#                     (omegaY/math.exp(lambdaX*abs(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,j])))*\
#                     (omegaX/math.exp(lambdaY*abs(batchedPositionTensor[batchI,timeStepI,0,i]-batchedPositionTensor[batchI,timeStepI,0,j])))
#                     if(batchedPositionTensor[batchI,timeStepI,1,i]-batchedPositionTensor[batchI,timeStepI,1,i]<0):
#                         #if i follows j, then multiple m, m<1
#                         adjacencyMatrix[i,j]=adjacencyMatrix[i,j]*m
#             adjacencyMatrix=adjacencyMatrix.unsqueeze(0)
            
#             #try fitting the map function with neural network
#             inputs=Variable(batchedPositionTensor[batchI,timeStepI,:,:].view(-1)).cuda()
#             lables=Variable(adjacencyMatrix.view(-1)).cuda()
#             outputs=mapNet(inputs)
#             loss=loss_MSE(outputs,lables)
#             print(outputs[0:10])
#             print(lables[0:10])
#             optimizer.zero_grad()

#             print(loss)
#             loss.backward()
#             optimizer.step()
            
            
            
#             if timeStepI==0:
#                 matrixSequenceInTimeStepDim=adjacencyMatrix
#             else:
#                 matrixSequenceInTimeStepDim=\
#                 torch.cat((matrixSequenceInTimeStepDim,adjacencyMatrix),0)
#         matrixSequenceInTimeStepDim=matrixSequenceInTimeStepDim.unsqueeze(0)
#         if batchI==0:
#             matrixSequenceInBatchDim=matrixSequenceInTimeStepDim
#         else:
#             matrixSequenceInBatchDim=torch.cat((matrixSequenceInBatchDim,matrixSequenceInTimeStepDim),0)            
#     return matrixSequenceInBatchDim
# torch.cuda.empty_cache()
# generateAdjacencyMatrix(dataInputs[:,:,0:2,:],5,5,1,1,2.5)

torch.Size([4, 100, 2, 250])
batchI 0
timeStepI: 0


/home/wangyuchen/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([ 0.4692,  0.0469,  0.4272,  0.4634, -0.3572,  0.0631, -0.8156, -0.1434,
         0.3318, -0.3463], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.3866, 0.0365, 0.4255, 0.7478, 0.4504, 0.1000, 0.0457, 0.5955,
        0.0349], device='cuda:0')
tensor(0.3919, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 1
tensor([ 0.0478,  0.0277,  0.0562,  0.0078, -0.0487, -0.0199, -0.1013, -0.0141,
         0.0652, -0.0219], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.3851, 0.0365, 0.4250, 0.7432, 0.4508, 0.1001, 0.0452, 0.5930,
        0.0348], device='cuda:0')
tensor(0.3037, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 2
tensor([ 0.0488,  0.0274,  0.0547,  0.0105, -0.0465, -0.0163, -0.1088, -0.0175,
         0.0592, -0.0211], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.0893e-04, 3.6663e-02, 4.2636e-01, 7.3090e-01, 4.5335e-01,
        1.0076e-01, 4.4692e-02, 5.8499e-01, 3.4389e-02], device='cuda:0')
tensor(0.3074, device='cuda

tensor([ 0.2325,  0.0615,  0.1408,  0.2165,  0.0164,  0.1559, -0.5232, -0.1301,
         0.0756, -0.0173], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.0467e-04, 6.2274e-03, 1.6616e-04, 5.1909e-01, 3.2033e-01,
        1.6616e-04, 2.7715e-02, 4.0562e-01, 2.8282e-02], device='cuda:0')
tensor(0.2703, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 24
tensor([ 0.2898,  0.0474,  0.1205,  0.2208, -0.0261,  0.1623, -0.5701, -0.0972,
         0.1117, -0.0407], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.0352e-04, 6.1662e-03, 1.6374e-04, 5.1927e-01, 3.1384e-01,
        1.6374e-04, 2.7585e-02, 4.0350e-01, 2.8346e-02], device='cuda:0')
tensor(0.2719, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 25
tensor([ 0.2787,  0.0510,  0.1550,  0.2283,  0.0446,  0.1723, -0.5576, -0.1395,
         0.0746, -0.0105], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.0402e-04, 6.1397e-03, 1.6224e-04, 5.2232e-01, 3.1604e-01,
        1.6224e-04,

tensor([ 0.6886,  0.2238,  0.2059,  0.4369, -0.0118,  0.1899, -0.7704,  0.0660,
         0.1484, -0.0922], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.3816e-01, 8.6904e-02, 2.4891e-01, 7.8566e-04, 4.1804e-01,
        8.9664e-02, 5.0677e-01, 1.5591e-03, 7.7203e-03], device='cuda:0')
tensor(0.1980, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 46
tensor([ 0.7057,  0.2015,  0.2210,  0.4833, -0.0723,  0.1952, -0.7791,  0.0565,
         0.1401, -0.1153], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.3785e-01, 8.6810e-02, 2.4748e-01, 7.7360e-04, 4.1949e-01,
        8.9838e-02, 5.0742e-01, 1.5726e-03, 7.6267e-03], device='cuda:0')
tensor(0.1954, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 47
tensor([ 0.7213,  0.2403,  0.2073,  0.4347, -0.0226,  0.2135, -0.7636,  0.0913,
         0.1436, -0.0948], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000e+00, 3.3750e-01, 8.6732e-02, 2.4608e-01, 7.6200e-04, 4.2086e-01,
        9.0012e-02,

tensor([ 0.9889,  0.3967,  0.1826,  0.4411, -0.0919,  0.3445, -0.6909,  0.2986,
         0.0697, -0.0531], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.4437, 0.0771, 0.2037, 0.7151, 0.4646, 0.0777, 0.4412, 0.0015,
        0.0679], device='cuda:0')
tensor(0.1300, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 69
tensor([ 1.0139,  0.3877,  0.1758,  0.4296, -0.0907,  0.3329, -0.7202,  0.3276,
         0.0604, -0.0424], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.4521, 0.0770, 0.2021, 0.7190, 0.4662, 0.0775, 0.4366, 0.0015,
        0.0674], device='cuda:0')
tensor(0.1241, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 70
tensor([ 1.0085,  0.4144,  0.1810,  0.4261, -0.0834,  0.3584, -0.6768,  0.3110,
         0.0630, -0.0587], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.4568, 0.0770, 0.2005, 0.7229, 0.4679, 0.0774, 0.4320, 0.0015,
        0.0669], device='cuda:0')
tensor(0.1239, device='cuda:0', grad_fn=<MseLossBackward>)
timeSt

tensor([ 1.1174,  0.3906,  0.1305,  0.2951,  0.0242,  0.4766, -0.5753,  0.3761,
         0.1751, -0.0523], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.3682, 0.0882, 0.1901, 0.6166, 0.4475, 0.0924, 0.5199, 0.3124,
        0.0731], device='cuda:0')
tensor(0.0862, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 94
tensor([ 1.0982,  0.4027,  0.1248,  0.2926,  0.0305,  0.4672, -0.5507,  0.4032,
         0.1953, -0.0518], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.3647, 0.0890, 0.1935, 0.6054, 0.4346, 0.0935, 0.5333, 0.3182,
        0.0740], device='cuda:0')
tensor(0.0845, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 95
tensor([ 1.1175,  0.3883,  0.1270,  0.2856,  0.0318,  0.4787, -0.5655,  0.3872,
         0.1968, -0.0522], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.3627, 0.0893, 0.1956, 0.5983, 0.4236, 0.0936, 0.5409, 0.3218,
        0.0745], device='cuda:0')
tensor(0.0803, device='cuda:0', grad_fn=<MseLossBackward>)
timeSt

tensor([ 1.0742,  0.3321,  0.0659,  0.1634,  0.1401,  0.4833, -0.4603,  0.3210,
         0.1719,  0.1220], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.0055, 0.0055, 0.1053, 0.6568, 0.4243, 0.0092, 0.2030, 0.0470,
        0.5135], device='cuda:0')
tensor(0.0618, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 19
tensor([ 1.0891,  0.2832,  0.0572,  0.1434,  0.1488,  0.4796, -0.4471,  0.3219,
         0.1734,  0.1168], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.0053, 0.0053, 0.1077, 0.6644, 0.4242, 0.0089, 0.2042, 0.0484,
        0.5019], device='cuda:0')
tensor(0.0604, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 20
tensor([ 1.0735,  0.2954,  0.0580,  0.1545,  0.1517,  0.4764, -0.4549,  0.3093,
         0.1656,  0.1363], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.0051, 0.0051, 0.1107, 0.6605, 0.4295, 0.0086, 0.2053, 0.0498,
        0.4890], device='cuda:0')
tensor(0.0591, device='cuda:0', grad_fn=<MseLossBackward>)
timeSt

tensor([ 1.0774,  0.1534,  0.1262,  0.1451,  0.1972,  0.3733, -0.3765,  0.1934,
         0.1627,  0.1520], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2141, 0.4038, 0.5106, 0.0013, 0.1592, 0.0759, 0.0057, 0.0587,
        0.0014], device='cuda:0')
tensor(0.0396, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 43
tensor([ 1.0620,  0.1483,  0.1365,  0.1637,  0.1844,  0.3555, -0.3439,  0.2145,
         0.1632,  0.1490], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2141, 0.4038, 0.5107, 0.0013, 0.1592, 0.0763, 0.0057, 0.0584,
        0.0013], device='cuda:0')
tensor(0.0388, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 44
tensor([ 1.0755,  0.1588,  0.1465,  0.1594,  0.1933,  0.3616, -0.3673,  0.1797,
         0.1617,  0.1427], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2140, 0.4038, 0.5106, 0.0013, 0.1592, 0.0765, 0.0056, 0.0582,
        0.0013], device='cuda:0')
tensor(0.0381, device='cuda:0', grad_fn=<MseLossBackward>)
timeSt

tensor([ 1.0376,  0.1888,  0.2824,  0.2987,  0.1405,  0.2657, -0.2616,  0.2357,
         0.2562,  0.0675], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2203, 0.3962, 0.5143, 0.0503, 0.1543, 0.0815, 0.3986, 0.3826,
        0.0012], device='cuda:0')
tensor(0.0440, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 68
tensor([ 1.0436,  0.1934,  0.2956,  0.2976,  0.1434,  0.2422, -0.2849,  0.2351,
         0.2663,  0.0630], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2204, 0.3962, 0.5143, 0.0683, 0.1539, 0.0816, 0.3972, 0.3840,
        0.0012], device='cuda:0')
tensor(0.0410, device='cuda:0', grad_fn=<MseLossBackward>)
timeStepI: 69
tensor([ 1.0391,  0.1909,  0.2921,  0.3058,  0.1366,  0.2569, -0.2524,  0.2473,
         0.2675,  0.0613], device='cuda:0', grad_fn=<SliceBackward>)
tensor([1.0000, 0.2203, 0.3962, 0.5141, 0.0680, 0.1539, 0.0817, 0.3958, 0.3854,
        0.0012], device='cuda:0')
tensor(0.0376, device='cuda:0', grad_fn=<MseLossBackward>)
timeSt

KeyboardInterrupt: 